theme = 'notes'
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  noClasses = false
[markup.tableOfContents]
  endLevel = 4
[markup.goldmark.katex]
    enabled = true
    warnings = false
